name: domain_price
description: Calculate an estimated price for domain name.
version: 0.1.0

environment:
  sdk: ^3.0.6

dependencies:
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
