name: domain_price
description: >-
  Calculate an estimated price for domain name.
  Appraising all top and some second-level domains.
repository: https://github.com/signmotion/domain_price
topics:
  - domain
  - price
  - shopping
  - internet

# Compatible with https://semver.org
# Format:
#   version: major.minor.patch
# You can calculate the number version code by this formula:
#   code = m[A]jor * 100 * 100 + m[I]nor * 100 + [P]atch
# Otherwise: +AAIIPP
version: 0.1.4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ">=1.10.0 <2.0.0"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
